#!/bin/bash
set -x

function die()
{
        echo "ERROR: $1 " >&2
        exit 1
}

[ -z "$LOCAL_DIR" ] && die "LOCAL_DIR not specified"
[ -z "$TARGET" ]  && die "No package target specified"
[ -z "$PACKAGE" ] && die "No package name specified"
[ ! -d $LOCAL_DIR ] && die "$LOCAL_DIR doesnot exist"

DEB_DEIR="$LOCAL_DIR/deb"
cd $LOCAL_DIR

cd learnhadoop
MVN=`which mvn`

$MVN install

MVN_STATUS=$?
[ $MVN_STATUS -eq 0 ] ||  exit $MVN_STATUS

BASE_DIR="/usr/share/$PACKAGE/"
mdkir $DEB_DIR && cd $DEB_DIR
cp -r $LOCAL_DIR/package/DEBIAN/* .

mkdir -p .$BASE_DIR
cp -r target/*jar  .$BASE_DIR

find . -type f -exec sed -i "s/__PACKAGE__/$PACKAGE/g"; sed -i "s/_VERSION_/$VERSION/g" {} + 

